/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import java.awt.Image;
import java.awt.Toolkit;
import org.apache.commons.net.util.Base64;
import javax.swing.JOptionPane;
import model.LoginDAO;
import model.login;

/**
 *
 * @author maico
 */
public class CrearUsuario extends javax.swing.JFrame {
    private login lg = new login();
    private LoginDAO LDao= new LoginDAO();
    /**
     * Creates new form CrearUsuario
     */
    public CrearUsuario() {
        initComponents();
        setIconImage(getIconImage());
        setLocationRelativeTo(null);
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Image/iconoprincipal.png"));
        return retValue;
    }
    
    private static String encriptar(String contr){
        return new String(Base64.encodeBase64(contr.getBytes()));
    }

    public void valida() {
        String pass = String.copyValueOf(Jpw_contraseña.getPassword());
        String passencript = encriptar(pass);
        String pass2 = String.copyValueOf(Jpw_contraseña2.getPassword());
        String user = Jtf_usuario.getText();
        String email = Jtf_correo.getText();
        String nombre = Jtf_nombre.getText();
        String apellido = Jtf_apellido.getText();
        String rol = Jcb_rol.getSelectedItem().toString();
        
        if (!pass.isEmpty() && !pass2.isEmpty()&&!user.isEmpty()&&!email.isEmpty()&&!nombre.isEmpty()&&!apellido.isEmpty()) {
            if (pass.equals(pass2)) {
                lg.setNombre(nombre);
                lg.setApellido(apellido);
                lg.setEmail(email);
                lg.setPassword(passencript);
                lg.setUsername(user);
                lg.setRol(rol);
                LDao.registrar(lg);
                limpiar();
                JOptionPane.showMessageDialog(null, "Usuario Registrado", "Message: Create User", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden!", "Error: Password", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No deje campos vacios", "Error: No data", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void limpiar(){
        Jtf_nombre.setText("");
        Jtf_apellido.setText("");
        Jtf_correo.setText("");
        Jtf_usuario.setText("");
        Jpw_contraseña.setText("");
        Jpw_contraseña2.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_BG = new javax.swing.JPanel();
        JP_image = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Jlb_title = new javax.swing.JLabel();
        Jlb_nombre = new javax.swing.JLabel();
        Jlb_apellido = new javax.swing.JLabel();
        Jlb_usuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        Jlb_contraseñaigual = new javax.swing.JLabel();
        Jlb_rol = new javax.swing.JLabel();
        Jtf_nombre = new javax.swing.JTextField();
        Jtf_apellido = new javax.swing.JTextField();
        Jtf_usuario = new javax.swing.JTextField();
        Jbn_crear = new javax.swing.JButton();
        Jbn_atras = new javax.swing.JButton();
        Jcb_rol = new javax.swing.JComboBox<>();
        Jpw_contraseña = new javax.swing.JPasswordField();
        Jpw_contraseña2 = new javax.swing.JPasswordField();
        Jtf_correo = new javax.swing.JTextField();
        Jlb_correo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        JP_BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JP_image.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CrearUsuario.png"))); // NOI18N
        JP_image.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 500));

        JP_BG.add(JP_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 220, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Jlb_title.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        Jlb_title.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_title.setText("Crear Usuario");

        Jlb_nombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_nombre.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_nombre.setText("Nombre:");

        Jlb_apellido.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_apellido.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_apellido.setText("Apellido:");

        Jlb_usuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_usuario.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_usuario.setText("Username:");

        contraseña.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        contraseña.setForeground(new java.awt.Color(255, 102, 0));
        contraseña.setText("Contraseña:");

        Jlb_contraseñaigual.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_contraseñaigual.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_contraseñaigual.setText("<html>Repita la contraseña:<html>");

        Jlb_rol.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_rol.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_rol.setText("Rol:");

        Jtf_nombre.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_nombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N

        Jtf_apellido.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_apellido.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N

        Jtf_usuario.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_usuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N

        Jbn_crear.setBackground(new java.awt.Color(255, 102, 0));
        Jbn_crear.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jbn_crear.setForeground(new java.awt.Color(255, 255, 255));
        Jbn_crear.setText("Crear");
        Jbn_crear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbn_crearActionPerformed(evt);
            }
        });

        Jbn_atras.setBackground(new java.awt.Color(255, 102, 0));
        Jbn_atras.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Jbn_atras.setForeground(new java.awt.Color(255, 255, 255));
        Jbn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/atras.png"))); // NOI18N
        Jbn_atras.setText("Atras");
        Jbn_atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbn_atrasActionPerformed(evt);
            }
        });

        Jcb_rol.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jcb_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Asistente" }));
        Jcb_rol.setFocusable(false);

        Jpw_contraseña.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N

        Jpw_contraseña2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N

        Jtf_correo.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_correo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N

        Jlb_correo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_correo.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_correo.setText("Email:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jlb_apellido)
                            .addComponent(Jlb_usuario)
                            .addComponent(Jlb_rol)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Jlb_nombre)
                                .addGap(50, 50, 50)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Jlb_title)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Jcb_rol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Jtf_usuario)
                                            .addComponent(Jtf_apellido)
                                            .addComponent(Jtf_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                            .addComponent(Jtf_correo)))))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Jlb_contraseñaigual, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(contraseña)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(215, 215, 215)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Jpw_contraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Jpw_contraseña))))
                            .addComponent(Jlb_correo)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jbn_atras)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(Jbn_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jbn_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jlb_title)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_nombre)
                    .addComponent(Jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_apellido)
                    .addComponent(Jtf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_rol)
                    .addComponent(Jcb_rol, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_usuario)
                    .addComponent(Jtf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_correo)
                    .addComponent(Jtf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contraseña)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Jpw_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_contraseñaigual, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jpw_contraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jbn_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        JP_BG.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_BG, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbn_crearActionPerformed
        valida();
    }//GEN-LAST:event_Jbn_crearActionPerformed

    private void Jbn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbn_atrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_Jbn_atrasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP_BG;
    private javax.swing.JPanel JP_image;
    private javax.swing.JButton Jbn_atras;
    private javax.swing.JButton Jbn_crear;
    private javax.swing.JComboBox<String> Jcb_rol;
    private javax.swing.JLabel Jlb_apellido;
    private javax.swing.JLabel Jlb_contraseñaigual;
    private javax.swing.JLabel Jlb_correo;
    private javax.swing.JLabel Jlb_nombre;
    private javax.swing.JLabel Jlb_rol;
    private javax.swing.JLabel Jlb_title;
    private javax.swing.JLabel Jlb_usuario;
    private javax.swing.JPasswordField Jpw_contraseña;
    private javax.swing.JPasswordField Jpw_contraseña2;
    private javax.swing.JTextField Jtf_apellido;
    private javax.swing.JTextField Jtf_correo;
    private javax.swing.JTextField Jtf_nombre;
    private javax.swing.JTextField Jtf_usuario;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
