/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visual;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.ClienteDAO;
import model.Eventos;

/**
 *
 * @author maico
 */
public class JP_Cliente extends javax.swing.JPanel {
    Eventos event = new Eventos();
    Cliente cl = new Cliente();
    ClienteDAO cliente = new ClienteDAO();
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form JP_Cliente
     */
    public JP_Cliente() {
        initComponents();
        Jtf_id.setVisible(false);
    }
    
    public void BuscarClientes(String buscar){
        LimpiarTable();
        List<Cliente> buscarCl = cliente.Buscadorcliente(buscar);
        modelo = (DefaultTableModel) Jtable_cliente.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < buscarCl.size(); i++) {
            ob[0] = buscarCl.get(i).getId();
            ob[1] = buscarCl.get(i).getDni();
            ob[2] = buscarCl.get(i).getNombre();
            ob[3] = buscarCl.get(i).getTelefono();
            ob[4] = buscarCl.get(i).getDireccion();

            modelo.addRow(ob);
        }
        Jtable_cliente.setModel(modelo);
    }
    
    public void LimpiarTable() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    public void ListarCliente() {
        List<Cliente> listarCl = cliente.Listarcliente();
        modelo = (DefaultTableModel) Jtable_cliente.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < listarCl.size(); i++) {
            ob[0] = listarCl.get(i).getId();
            ob[1] = listarCl.get(i).getDni();
            ob[2] = listarCl.get(i).getNombre();
            ob[3] = listarCl.get(i).getTelefono();
            ob[4] = listarCl.get(i).getDireccion();

            modelo.addRow(ob);
        }
        Jtable_cliente.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_BG = new javax.swing.JPanel();
        Jlb_dniruc = new javax.swing.JLabel();
        Jlb_nombre = new javax.swing.JLabel();
        Jlb_telefono = new javax.swing.JLabel();
        Jlb_direccion = new javax.swing.JLabel();
        Jtf_id = new javax.swing.JTextField();
        Jtf_dniruc = new javax.swing.JTextField();
        Jtf_nombre = new javax.swing.JTextField();
        Jtf_telefono = new javax.swing.JTextField();
        Jtf_direccion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtable_cliente = new javax.swing.JTable();
        Jbn_guardar = new javax.swing.JButton();
        Jbn_actualizar = new javax.swing.JButton();
        Jbn_eliminar = new javax.swing.JButton();
        Jbn_nuevo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        Jlb_buscar = new javax.swing.JLabel();
        Jtf_buscador = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        JP_BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jlb_dniruc.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_dniruc.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_dniruc.setText("DNI/RUC:");

        Jlb_nombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_nombre.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_nombre.setText("Nombre:");

        Jlb_telefono.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_telefono.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_telefono.setText("Telefono:");

        Jlb_direccion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_direccion.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_direccion.setText("Dirección:");

        Jtf_id.setEditable(false);
        Jtf_id.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_id.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jtf_id.setForeground(new java.awt.Color(255, 102, 0));
        Jtf_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Jtf_id.setBorder(null);
        Jtf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_idActionPerformed(evt);
            }
        });

        Jtf_dniruc.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_dniruc.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jtf_dniruc.setForeground(new java.awt.Color(0, 0, 0));
        Jtf_dniruc.setBorder(null);
        Jtf_dniruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_dnirucKeyTyped(evt);
            }
        });

        Jtf_nombre.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_nombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jtf_nombre.setForeground(new java.awt.Color(0, 0, 0));
        Jtf_nombre.setBorder(null);
        Jtf_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_nombreKeyTyped(evt);
            }
        });

        Jtf_telefono.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_telefono.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jtf_telefono.setForeground(new java.awt.Color(0, 0, 0));
        Jtf_telefono.setBorder(null);
        Jtf_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_telefonoKeyTyped(evt);
            }
        });

        Jtf_direccion.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_direccion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jtf_direccion.setForeground(new java.awt.Color(0, 0, 0));
        Jtf_direccion.setBorder(null);

        Jtable_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI/RUC", "NOMBRE", "TELEFONO", "DIRECCIÓN"
            }
        ));
        Jtable_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jtable_clienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Jtable_cliente);
        if (Jtable_cliente.getColumnModel().getColumnCount() > 0) {
            Jtable_cliente.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        Jbn_guardar.setBackground(new java.awt.Color(255, 102, 0));
        Jbn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_guardar.png"))); // NOI18N
        Jbn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbn_guardarActionPerformed(evt);
            }
        });

        Jbn_actualizar.setBackground(new java.awt.Color(255, 102, 0));
        Jbn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_actualizar.png"))); // NOI18N
        Jbn_actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbn_actualizarActionPerformed(evt);
            }
        });

        Jbn_eliminar.setBackground(new java.awt.Color(255, 102, 0));
        Jbn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_eliminar.png"))); // NOI18N
        Jbn_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbn_eliminarActionPerformed(evt);
            }
        });

        Jbn_nuevo.setBackground(new java.awt.Color(255, 102, 0));
        Jbn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_nuevo.png"))); // NOI18N
        Jbn_nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbn_nuevoActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 102, 0));

        jSeparator2.setForeground(new java.awt.Color(255, 102, 0));

        jSeparator3.setForeground(new java.awt.Color(255, 102, 0));

        jSeparator4.setForeground(new java.awt.Color(255, 102, 0));

        Jlb_buscar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_buscar.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_buscar.setText("Buscar:");

        Jtf_buscador.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_buscador.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jtf_buscador.setForeground(new java.awt.Color(0, 0, 0));
        Jtf_buscador.setBorder(null);
        Jtf_buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Jtf_buscadorKeyReleased(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JP_BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jlb_dniruc)
                        .addGap(37, 37, 37)
                        .addComponent(Jtf_dniruc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(121, 121, 121)
                            .addComponent(jSeparator1))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Jlb_nombre)
                                .addComponent(Jlb_telefono)
                                .addComponent(Jlb_direccion))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator4)
                                .addComponent(jSeparator2)
                                .addComponent(Jtf_telefono)
                                .addComponent(Jtf_nombre)
                                .addComponent(Jtf_direccion)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Jbn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Jbn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Jbn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Jbn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jlb_buscar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator5)
                            .addComponent(Jtf_buscador, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JP_BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jlb_buscar)
                            .addComponent(Jtf_buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jlb_dniruc)
                            .addComponent(Jtf_dniruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jlb_nombre)
                            .addComponent(Jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jlb_telefono)
                            .addComponent(Jtf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jlb_direccion)
                            .addComponent(Jtf_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Jbn_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jbn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jbn_nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jbn_guardar))
                        .addGap(18, 18, 18)
                        .addComponent(Jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Jbn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbn_guardarActionPerformed
        if (!Jtf_dniruc.getText().isEmpty() || !Jtf_nombre.getText().isEmpty() || !Jtf_direccion.getText().isEmpty() || !Jtf_telefono.getText().isEmpty()) {

            if (Jtf_dniruc.getText().isEmpty()) {
                cl.setDni(0);
            } else {
                cl.setDni(Integer.parseInt(Jtf_dniruc.getText()));
            }
            cl.setNombre(Jtf_nombre.getText());
            cl.setTelefono(Jtf_telefono.getText());
            cl.setDireccion(Jtf_direccion.getText());

            cliente.RegistrarCliente(cl);
            LimpiarJtf();
            LimpiarTable();
            ListarCliente();
            JOptionPane.showMessageDialog(null, "Cliente Registrado", "Message: Customer", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "No deje campos vacios!", "Error: No data", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Jbn_guardarActionPerformed

    private void Jtable_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jtable_clienteMouseClicked
        int fila = Jtable_cliente.rowAtPoint(evt.getPoint());
        Jtf_id.setText(Jtable_cliente.getValueAt(fila, 0).toString());
        Jtf_dniruc.setText(Jtable_cliente.getValueAt(fila, 1).toString());
        Jtf_nombre.setText(Jtable_cliente.getValueAt(fila, 2).toString());
        Jtf_telefono.setText(Jtable_cliente.getValueAt(fila, 3).toString());
        Jtf_direccion.setText(Jtable_cliente.getValueAt(fila, 4).toString());
    }//GEN-LAST:event_Jtable_clienteMouseClicked

    private void Jbn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbn_eliminarActionPerformed
        if (!Jtf_id.getText().isEmpty()) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar?");
            if (pregunta == 0) {
                int id = Integer.parseInt(Jtf_id.getText());
                cliente.EliminarCliente(id);
                LimpiarJtf();
                LimpiarTable();
                ListarCliente();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione el cliente", "Error: No data", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Jbn_eliminarActionPerformed

    private void Jbn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbn_nuevoActionPerformed
        LimpiarJtf();
    }//GEN-LAST:event_Jbn_nuevoActionPerformed

    private void Jbn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbn_actualizarActionPerformed
        if (!Jtf_id.getText().isEmpty()) {
            if (!Jtf_dniruc.getText().isEmpty() || !Jtf_nombre.getText().isEmpty() || !Jtf_direccion.getText().isEmpty() || !Jtf_telefono.getText().isEmpty()) {
                cl.setDni(Integer.parseInt(Jtf_dniruc.getText()));
                cl.setNombre(Jtf_nombre.getText());
                cl.setTelefono(Jtf_telefono.getText());
                cl.setDireccion(Jtf_direccion.getText());
                cl.setId(Integer.parseInt(Jtf_id.getText()));
                cliente.ModificarCliente(cl);
                LimpiarJtf();
                LimpiarTable();
                ListarCliente();
            } else {
                JOptionPane.showMessageDialog(null, "No deje campos vacios!", "Message: No data", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione el cliente", "Message: No data", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Jbn_actualizarActionPerformed

    private void Jtf_dnirucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_dnirucKeyTyped
        event.numberKeyPress(evt);
    }//GEN-LAST:event_Jtf_dnirucKeyTyped

    private void Jtf_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_telefonoKeyTyped
        event.numberKeyPress(evt);
        event.txtCelularKeyTyped(evt, Jtf_telefono);
    }//GEN-LAST:event_Jtf_telefonoKeyTyped

    private void Jtf_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_nombreKeyTyped
        event.textKeyPress(evt);
    }//GEN-LAST:event_Jtf_nombreKeyTyped

    private void Jtf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_idActionPerformed

    private void Jtf_buscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_buscadorKeyReleased
        BuscarClientes(Jtf_buscador.getText());
    }//GEN-LAST:event_Jtf_buscadorKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP_BG;
    private javax.swing.JButton Jbn_actualizar;
    private javax.swing.JButton Jbn_eliminar;
    private javax.swing.JButton Jbn_guardar;
    private javax.swing.JButton Jbn_nuevo;
    private javax.swing.JLabel Jlb_buscar;
    private javax.swing.JLabel Jlb_direccion;
    private javax.swing.JLabel Jlb_dniruc;
    private javax.swing.JLabel Jlb_nombre;
    private javax.swing.JLabel Jlb_telefono;
    private javax.swing.JTable Jtable_cliente;
    private javax.swing.JTextField Jtf_buscador;
    private javax.swing.JTextField Jtf_direccion;
    private javax.swing.JTextField Jtf_dniruc;
    private javax.swing.JTextField Jtf_id;
    private javax.swing.JTextField Jtf_nombre;
    private javax.swing.JTextField Jtf_telefono;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
    public void LimpiarJtf() {
        Jtf_id.setText("");
        Jtf_dniruc.setText("");
        Jtf_nombre.setText("");
        Jtf_telefono.setText("");
        Jtf_direccion.setText("");
    }
}
