/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visual;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Config;
import model.Eventos;
import model.Productos;
import model.ProductosDAO;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author maico
 */
public class JP_Productos extends javax.swing.JPanel {

    Eventos event = new Eventos();
    Productos p = new Productos();
    ProductosDAO produc = new ProductosDAO();
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form JP_Productos
     */
    public JP_Productos() {
        initComponents();
        Jtf_id.setVisible(false);
        AutoCompleteDecorator.decorate(Jcb_proveedor);
    }

    public void LimpiarTable() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    public void LimpiarJCB() {
        Jcb_proveedor.removeAllItems();
    }

    public void BuscarProductos(String buscar) {
        LimpiarTable();
        List<Productos> buscarP = produc.BuscarProducto(buscar);
        modelo = (DefaultTableModel) Jtable_productos.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < buscarP.size(); i++) {
            ob[0] = buscarP.get(i).getId();
            ob[1] = buscarP.get(i).getCodigo();
            ob[2] = buscarP.get(i).getProducto();
            ob[3] = buscarP.get(i).getStock();
            ob[4] = buscarP.get(i).getPrecio();
            ob[5] = buscarP.get(i).getProveedor();

            modelo.addRow(ob);
        }
        Jtable_productos.setModel(modelo);
    }

    public void ListarProductos() {
        List<Productos> listarP = produc.ListarProducto();
        modelo = (DefaultTableModel) Jtable_productos.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < listarP.size(); i++) {
            ob[0] = listarP.get(i).getId();
            ob[1] = listarP.get(i).getCodigo();
            ob[2] = listarP.get(i).getProducto();
            ob[3] = listarP.get(i).getStock();
            ob[4] = listarP.get(i).getPrecio();
            ob[5] = listarP.get(i).getProveedor();
            modelo.addRow(ob);
        }
        Jtable_productos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_BG = new javax.swing.JPanel();
        Jlb_codigo = new javax.swing.JLabel();
        Jlb_descripcion = new javax.swing.JLabel();
        Jlb_cantidad = new javax.swing.JLabel();
        Jlb_precio = new javax.swing.JLabel();
        Jlb_Buscar = new javax.swing.JLabel();
        Jlb_proveedor = new javax.swing.JLabel();
        Jtf_codigo = new javax.swing.JTextField();
        Jtf_descripcion = new javax.swing.JTextField();
        Jtf_cantidad = new javax.swing.JTextField();
        Jtf_precio = new javax.swing.JTextField();
        Jtf_id = new javax.swing.JTextField();
        Jtf_buscador = new javax.swing.JTextField();
        Jcb_proveedor = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtable_productos = new javax.swing.JTable();
        Jbn_guardar = new javax.swing.JButton();
        Jbn_actualizar = new javax.swing.JButton();
        Jbn_eliminar = new javax.swing.JButton();
        Jbn_nuevo = new javax.swing.JButton();
        Jbn_generarReporte = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(1050, 660));

        JP_BG.setBackground(new java.awt.Color(255, 255, 255));

        Jlb_codigo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_codigo.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_codigo.setText("Codigo:");

        Jlb_descripcion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_descripcion.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_descripcion.setText("Descripción:");

        Jlb_cantidad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_cantidad.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_cantidad.setText("Cantidad:");

        Jlb_precio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_precio.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_precio.setText("Precio:");

        Jlb_Buscar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_Buscar.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_Buscar.setText("Buscar:");

        Jlb_proveedor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_proveedor.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_proveedor.setText("Proveedor:");

        Jtf_codigo.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_codigo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jtf_codigo.setForeground(new java.awt.Color(0, 0, 0));
        Jtf_codigo.setBorder(null);
        Jtf_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_codigoKeyTyped(evt);
            }
        });

        Jtf_descripcion.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_descripcion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jtf_descripcion.setForeground(new java.awt.Color(0, 0, 0));
        Jtf_descripcion.setBorder(null);
        Jtf_descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_descripcionKeyTyped(evt);
            }
        });

        Jtf_cantidad.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_cantidad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jtf_cantidad.setForeground(new java.awt.Color(0, 0, 0));
        Jtf_cantidad.setBorder(null);
        Jtf_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_cantidadKeyTyped(evt);
            }
        });

        Jtf_precio.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_precio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jtf_precio.setForeground(new java.awt.Color(0, 0, 0));
        Jtf_precio.setBorder(null);
        Jtf_precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_precioKeyTyped(evt);
            }
        });

        Jtf_id.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_id.setBorder(null);

        Jtf_buscador.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_buscador.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jtf_buscador.setForeground(new java.awt.Color(0, 0, 0));
        Jtf_buscador.setBorder(null);
        Jtf_buscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_buscadorActionPerformed(evt);
            }
        });
        Jtf_buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Jtf_buscadorKeyReleased(evt);
            }
        });

        Jcb_proveedor.setBackground(new java.awt.Color(255, 255, 255));
        Jcb_proveedor.setEditable(true);
        Jcb_proveedor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N

        Jtable_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CODIGO", " DESCRICIÓN", "CANTIDAD", "PRECIO", "PROVEEDOR"
            }
        ));
        Jtable_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jtable_productosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Jtable_productos);
        if (Jtable_productos.getColumnModel().getColumnCount() > 0) {
            Jtable_productos.getColumnModel().getColumn(0).setPreferredWidth(30);
            Jtable_productos.getColumnModel().getColumn(1).setPreferredWidth(40);
            Jtable_productos.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        Jbn_guardar.setBackground(new java.awt.Color(255, 102, 0));
        Jbn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_guardar.png"))); // NOI18N
        Jbn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbn_guardarActionPerformed(evt);
            }
        });

        Jbn_actualizar.setBackground(new java.awt.Color(255, 102, 0));
        Jbn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_actualizar.png"))); // NOI18N
        Jbn_actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbn_actualizarActionPerformed(evt);
            }
        });

        Jbn_eliminar.setBackground(new java.awt.Color(255, 102, 0));
        Jbn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_eliminar.png"))); // NOI18N
        Jbn_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbn_eliminarActionPerformed(evt);
            }
        });

        Jbn_nuevo.setBackground(new java.awt.Color(255, 102, 0));
        Jbn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nuevo-producto.png"))); // NOI18N
        Jbn_nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbn_nuevoActionPerformed(evt);
            }
        });

        Jbn_generarReporte.setBackground(new java.awt.Color(255, 102, 0));
        Jbn_generarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PDF.png"))); // NOI18N
        Jbn_generarReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbn_generarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbn_generarReporteActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 102, 0));

        jSeparator2.setForeground(new java.awt.Color(255, 102, 0));

        jSeparator3.setForeground(new java.awt.Color(255, 102, 0));

        jSeparator4.setForeground(new java.awt.Color(255, 102, 0));

        jSeparator5.setForeground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout JP_BGLayout = new javax.swing.GroupLayout(JP_BG);
        JP_BG.setLayout(JP_BGLayout);
        JP_BGLayout.setHorizontalGroup(
            JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_BGLayout.createSequentialGroup()
                .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_BGLayout.createSequentialGroup()
                        .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP_BGLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Jlb_descripcion)
                                    .addComponent(Jlb_cantidad)
                                    .addComponent(Jlb_precio)
                                    .addComponent(Jlb_codigo)
                                    .addComponent(Jlb_proveedor))
                                .addGap(29, 29, 29)
                                .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator3)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jtf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jtf_cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(Jtf_descripcion)
                                    .addComponent(Jtf_precio)
                                    .addComponent(jSeparator2)
                                    .addComponent(jSeparator4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_BGLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_BGLayout.createSequentialGroup()
                                .addComponent(Jlb_Buscar)
                                .addGap(18, 18, 18)
                                .addComponent(Jtf_buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JP_BGLayout.createSequentialGroup()
                        .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP_BGLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JP_BGLayout.createSequentialGroup()
                                        .addComponent(Jbn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Jbn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Jbn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Jbn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Jbn_generarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(JP_BGLayout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(Jcb_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        JP_BGLayout.setVerticalGroup(
            JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_BGLayout.createSequentialGroup()
                .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_BGLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jtf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jlb_codigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JP_BGLayout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Jlb_Buscar)
                                .addComponent(Jtf_buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_BGLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9))))
                .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_BGLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jlb_descripcion)
                            .addComponent(Jtf_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jlb_cantidad)
                            .addComponent(Jtf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jlb_precio)
                            .addComponent(Jtf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jlb_proveedor)
                            .addComponent(Jcb_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jbn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jbn_eliminar)
                            .addComponent(Jbn_actualizar)
                            .addComponent(Jbn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Jbn_generarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(Jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JP_BGLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JP_BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Jbn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbn_actualizarActionPerformed
        if (!Jtf_id.getText().isEmpty()) {
            if (!Jtf_codigo.getText().isEmpty() || !Jtf_descripcion.getText().isEmpty() || !Jtf_cantidad.getText().isEmpty() || !Jtf_precio.getText().isEmpty() && !Jcb_proveedor.getSelectedItem().toString().isEmpty()) {
                p.setCodigo(Jtf_codigo.getText());
                p.setProducto(Jtf_descripcion.getText());
                p.setPrecio(Double.parseDouble(Jtf_precio.getText()));
                p.setStock(Integer.parseInt(Jtf_cantidad.getText()));
                p.setProveedor(Jcb_proveedor.getSelectedItem().toString());
                p.setId(Integer.parseInt(Jtf_id.getText()));

                produc.ModificarProducto(p);

                LimpiarJtf();
                LimpiarTable();
                ListarProductos();
            } else {
                JOptionPane.showMessageDialog(null, "No deje campos vacios!", "Message: No data", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione el producto", "Message: No data", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Jbn_actualizarActionPerformed

    private void Jbn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbn_guardarActionPerformed
        if (!Jtf_codigo.getText().isEmpty() && !Jtf_descripcion.getText().isEmpty() && !Jtf_cantidad.getText().isEmpty() && !Jtf_precio.getText().isEmpty() && !Jcb_proveedor.getSelectedItem().toString().isEmpty()) {
            p.setCodigo(Jtf_codigo.getText());
            p.setProducto(Jtf_descripcion.getText());
            p.setPrecio(Double.parseDouble(Jtf_precio.getText()));
            p.setStock(Integer.parseInt(Jtf_cantidad.getText()));
            p.setProveedor(Jcb_proveedor.getSelectedItem().toString());

            produc.RegistrarProducto(p);
            LimpiarJtf();
            LimpiarTable();
            ListarProductos();
            JOptionPane.showMessageDialog(null, "Producto registrado", "Message: Registration", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "No deje campos vacios!", "Error: No data", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Jbn_guardarActionPerformed

    private void Jbn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbn_nuevoActionPerformed
        LimpiarJtf();
    }//GEN-LAST:event_Jbn_nuevoActionPerformed

    private void Jtable_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jtable_productosMouseClicked
        int fila = Jtable_productos.rowAtPoint(evt.getPoint());
        Jtf_id.setText(Jtable_productos.getValueAt(fila, 0).toString());
        Jtf_codigo.setText(Jtable_productos.getValueAt(fila, 1).toString());
        Jtf_descripcion.setText(Jtable_productos.getValueAt(fila, 2).toString());
        Jtf_cantidad.setText(Jtable_productos.getValueAt(fila, 3).toString());
        Jtf_precio.setText(Jtable_productos.getValueAt(fila, 4).toString());
        Jcb_proveedor.setSelectedItem(Jtable_productos.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_Jtable_productosMouseClicked

    private void Jtf_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_codigoKeyTyped
        event.numberKeyPress(evt);
    }//GEN-LAST:event_Jtf_codigoKeyTyped

    private void Jtf_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_cantidadKeyTyped
        event.numberKeyPress(evt);
    }//GEN-LAST:event_Jtf_cantidadKeyTyped

    private void Jtf_precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_precioKeyTyped
        event.numberDecimalKeyPress(evt, Jtf_precio);
    }//GEN-LAST:event_Jtf_precioKeyTyped

    private void Jbn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbn_eliminarActionPerformed
        if (!Jtf_id.getText().isEmpty()) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar?");
            if (pregunta == 0) {
                int id = Integer.parseInt(Jtf_id.getText());
                produc.EliminarProducto(id);
                LimpiarJtf();
                LimpiarTable();
                ListarProductos();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione el producto", "Error: Dato vacio", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Jbn_eliminarActionPerformed

    private void Jbn_generarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbn_generarReporteActionPerformed
        try {
            pdf();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JP_Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Jbn_generarReporteActionPerformed

    private void Jtf_descripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_descripcionKeyTyped
        event.textKeyPress(evt);
    }//GEN-LAST:event_Jtf_descripcionKeyTyped

    private void Jtf_buscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_buscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_buscadorActionPerformed

    private void Jtf_buscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_buscadorKeyReleased
        BuscarProductos(Jtf_buscador.getText());
    }//GEN-LAST:event_Jtf_buscadorKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP_BG;
    private javax.swing.JButton Jbn_actualizar;
    private javax.swing.JButton Jbn_eliminar;
    private javax.swing.JButton Jbn_generarReporte;
    private javax.swing.JButton Jbn_guardar;
    private javax.swing.JButton Jbn_nuevo;
    public javax.swing.JComboBox<String> Jcb_proveedor;
    private javax.swing.JLabel Jlb_Buscar;
    private javax.swing.JLabel Jlb_cantidad;
    private javax.swing.JLabel Jlb_codigo;
    private javax.swing.JLabel Jlb_descripcion;
    private javax.swing.JLabel Jlb_precio;
    private javax.swing.JLabel Jlb_proveedor;
    private javax.swing.JTable Jtable_productos;
    private javax.swing.JTextField Jtf_buscador;
    private javax.swing.JTextField Jtf_cantidad;
    private javax.swing.JTextField Jtf_codigo;
    private javax.swing.JTextField Jtf_descripcion;
    private javax.swing.JTextField Jtf_id;
    private javax.swing.JTextField Jtf_precio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
    private void LimpiarJtf() {
        Jtf_codigo.setText("");
        Jtf_descripcion.setText("");
        Jtf_cantidad.setText("");
        Jtf_precio.setText("");
    }

    private void pdf() throws FileNotFoundException {
        Document documento = new Document();
        try {
            String ruta = System.getProperty("user.home");
            
            File directorio = new File(ruta+"/Documents/facturas");
            if (!directorio.exists()) {
                if (directorio.mkdirs()) {
                    JOptionPane.showMessageDialog(null, "Directorio creado en documentos", "Message: DIR", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Error al crear el directorio", "ERROR: DIR", JOptionPane.ERROR_MESSAGE);
                }
            }

            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Documents/facturas/Productos.pdf"));
            documento.open();

            Image img = Image.getInstance("src/Image/icono.png");
            Paragraph fech = new Paragraph();
            Font negrita = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD, BaseColor.BLUE);
            fech.add(Chunk.NEWLINE);
            Date date = new Date();
            fech.add("Fecha: " + new SimpleDateFormat("dd-MM-yyyy").format(date) + "\n\n");

            PdfPTable Encabezado = new PdfPTable(4);
            Encabezado.setWidthPercentage(100);
            Encabezado.getDefaultCell().setBorder(0);
            float[] ColumnaEncabezado = new float[]{20f, 30f, 70f, 40f};
            Encabezado.setWidths(ColumnaEncabezado);
            Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);

            Encabezado.addCell(img);
            Config conf = new Config();
            ProductosDAO proDao = new ProductosDAO();
            conf = proDao.BuscarDatos();

            String ruc = "" + conf.getCc();
            String nom = "" + conf.getNombre();
            String tel = "" + conf.getTelefono();
            String dir = "" + conf.getDireccion();

            PdfPCell cell1 = new PdfPCell(new Phrase(""));
            cell1.setBorder(0);
            Encabezado.addCell(cell1);

            PdfPCell cell2 = new PdfPCell(new Phrase("Ruc: " + ruc + "\nNombre: " + nom + "\nTelefono: " + tel + "\nDireccion: " + dir));
            cell2.setBorder(0);
            Encabezado.addCell(cell2);

            PdfPCell cell3 = new PdfPCell(fech);
            cell3.setBorder(0);
            Encabezado.addCell(cell3);

            PdfPCell cell4 = new PdfPCell(new Phrase(""));
            cell4.setBorder(0);
            Encabezado.addCell(cell4);

            documento.add(Encabezado);

            Paragraph pro = new Paragraph();
            pro.add(Chunk.NEWLINE);
            pro.add("Productos existentes" + "\n\n");
            pro.setAlignment(Element.ALIGN_CENTER);
            documento.add(pro);

            //productos
            PdfPTable tablaPro = new PdfPTable(6);
            Encabezado.setWidthPercentage(100);
            Encabezado.getDefaultCell().setBorder(0);
            float[] ColumnaPro = new float[]{10f, 50f, 15f, 20f};
            Encabezado.setWidths(ColumnaPro);
            Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell pro1 = new PdfPCell(new Phrase("codigo", negrita));
            PdfPCell pro2 = new PdfPCell(new Phrase("Cant.", negrita));
            PdfPCell pro3 = new PdfPCell(new Phrase("Descripción", negrita));
            PdfPCell pro4 = new PdfPCell(new Phrase("Precio U.", negrita));
            PdfPCell pro5 = new PdfPCell(new Phrase("Provee.", negrita));
            PdfPCell pro6 = new PdfPCell(new Phrase("Fecha", negrita));
            pro1.setBorder(0);
            pro2.setBorder(0);
            pro3.setBorder(0);
            pro4.setBorder(0);
            pro5.setBorder(0);
            pro6.setBorder(0);
            pro1.setBackgroundColor(BaseColor.DARK_GRAY);
            pro2.setBackgroundColor(BaseColor.DARK_GRAY);
            pro3.setBackgroundColor(BaseColor.DARK_GRAY);
            pro4.setBackgroundColor(BaseColor.DARK_GRAY);
            pro5.setBackgroundColor(BaseColor.DARK_GRAY);
            pro6.setBackgroundColor(BaseColor.DARK_GRAY);
            tablaPro.addCell(pro1);
            tablaPro.addCell(pro2);
            tablaPro.addCell(pro3);
            tablaPro.addCell(pro4);
            tablaPro.addCell(pro5);
            tablaPro.addCell(pro6);

            List<Productos> listarP = produc.ListarProducto();
            for (int i = 0; i < listarP.size(); i++) {
                String codigo = listarP.get(i).getCodigo();
                String producto = listarP.get(i).getProducto();
                String cantidad = ""+listarP.get(i).getStock();
                String  precio= ""+listarP.get(i).getPrecio();
                String provee = listarP.get(i).getProveedor();
                String fecha = listarP.get(i).getFecha();
                tablaPro.addCell(codigo);
                tablaPro.addCell(cantidad);
                tablaPro.addCell(producto);
                tablaPro.addCell(precio);
                tablaPro.addCell(provee);
                tablaPro.addCell(fecha);
            }

            documento.add(tablaPro);

            Paragraph firma = new Paragraph();
            firma.add(Chunk.NEWLINE);
            firma.add("Ferelinares\n\n");
            firma.add("-----------------------------");
            firma.setAlignment(Element.ALIGN_CENTER);
            documento.add(firma);

            Paragraph mensaje = new Paragraph();
            mensaje.add(Chunk.NEWLINE);
            mensaje.add("Gracias por su Compra.");
            mensaje.setAlignment(Element.ALIGN_CENTER);
            documento.add(mensaje);

            documento.close();
            Desktop.getDesktop().open(new File(ruta + "/Documents/facturas/Productos.pdf"));

        } catch (DocumentException | IOException e) {
            JOptionPane.showMessageDialog(null, e.toString(), "Error: pdf", JOptionPane.ERROR_MESSAGE);
        }
    }
}
