/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visual;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.TablaListener;
import model.Venta;
import model.VentaDAO;

/**
 *
 * @author maico
 */
public class JP_Ventas extends javax.swing.JPanel implements TablaListener{

    Venta v = new Venta();
    VentaDAO vDAO = new VentaDAO();
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form JP_ventas
     */
    public JP_Ventas() {
        initComponents();
        Jlb_id.setVisible(false);
    }
    
    public void tablaActualizada() {
        LimpiarTable();
        listarVenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_BG = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtable_ventas = new javax.swing.JTable();
        Jbt_verVenta = new javax.swing.JButton();
        Jlb_id = new javax.swing.JLabel();
        Jlb_buscar = new javax.swing.JLabel();
        Jtf_buscador = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Jbt_abonar = new javax.swing.JButton();

        JP_BG.setBackground(new java.awt.Color(255, 255, 255));

        Jtable_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CLIENTE", "VENDEDOR", "PAGO", "TOTAL", "ABONO", "SALDO", "FECHA"
            }
        ));
        Jtable_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jtable_ventasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Jtable_ventas);
        if (Jtable_ventas.getColumnModel().getColumnCount() > 0) {
            Jtable_ventas.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        Jbt_verVenta.setBackground(new java.awt.Color(255, 102, 0));
        Jbt_verVenta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jbt_verVenta.setForeground(new java.awt.Color(255, 255, 255));
        Jbt_verVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/factura_2.png"))); // NOI18N
        Jbt_verVenta.setText("Ver venta");
        Jbt_verVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbt_verVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbt_verVentaActionPerformed(evt);
            }
        });

        Jlb_buscar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_buscar.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_buscar.setText("Buscar:");

        Jtf_buscador.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_buscador.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jtf_buscador.setForeground(new java.awt.Color(0, 0, 0));
        Jtf_buscador.setBorder(null);
        Jtf_buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Jtf_buscadorKeyReleased(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 102, 0));

        Jbt_abonar.setBackground(new java.awt.Color(255, 102, 0));
        Jbt_abonar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jbt_abonar.setForeground(new java.awt.Color(255, 255, 255));
        Jbt_abonar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Abonar.png"))); // NOI18N
        Jbt_abonar.setText("Abonar Factura");
        Jbt_abonar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbt_abonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbt_abonarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_BGLayout = new javax.swing.GroupLayout(JP_BG);
        JP_BG.setLayout(JP_BGLayout);
        JP_BGLayout.setHorizontalGroup(
            JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_BGLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JP_BGLayout.createSequentialGroup()
                        .addComponent(Jbt_verVenta)
                        .addGap(18, 18, 18)
                        .addComponent(Jbt_abonar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jlb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jlb_buscar)
                        .addGap(18, 18, 18)
                        .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(Jtf_buscador, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        JP_BGLayout.setVerticalGroup(
            JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_BGLayout.createSequentialGroup()
                .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_BGLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jbt_verVenta)
                            .addComponent(Jbt_abonar)))
                    .addGroup(JP_BGLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(JP_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jlb_buscar)
                            .addComponent(Jtf_buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JP_BGLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Jlb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JP_BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JP_BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Jbt_verVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbt_verVentaActionPerformed
        if (!Jlb_id.getText().equals("")) {
            try {
                int id = Integer.parseInt(Jlb_id.getText());
                String ruta = System.getProperty("user.home");
                File file = new File(ruta + "/Documents/facturas/venta_" + id + ".pdf");
                Desktop.getDesktop().open(file);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex.toString(), "Error: pdf", JOptionPane.ERROR_MESSAGE);
                java.util.logging.Logger.getLogger(JP_Ventas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una venta", "Message: Invoice", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Jbt_verVentaActionPerformed

    private void Jtable_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jtable_ventasMouseClicked
        int fila = Jtable_ventas.rowAtPoint(evt.getPoint());
        Jlb_id.setText(Jtable_ventas.getValueAt(fila, 0).toString());
        v.setId(Integer.parseInt(Jlb_id.getText()));
        v.setCliente(Jtable_ventas.getValueAt(fila, 1).toString());
        v.setTipo_pago(Jtable_ventas.getValueAt(fila, 3).toString());
        v.setTotal(Double.parseDouble(Jtable_ventas.getValueAt(fila, 4).toString()));
        v.setAbono(Double.parseDouble(Jtable_ventas.getValueAt(fila, 5).toString()));
        v.setSaldo(Double.parseDouble(Jtable_ventas.getValueAt(fila, 6).toString()));
    }//GEN-LAST:event_Jtable_ventasMouseClicked

    private void Jtf_buscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_buscadorKeyReleased
        BuscarVentas(Jtf_buscador.getText());
    }//GEN-LAST:event_Jtf_buscadorKeyReleased

    private void Jbt_abonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbt_abonarActionPerformed
        if (!Jlb_id.getText().equals("")) {
            if (v.getSaldo()>0.0) {
                PagarSaldo pg = new PagarSaldo(v);
                pg.setTablaListener(this);
                pg.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Esta factura ya está pagada");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una venta", "Message: Invoice", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Jbt_abonarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP_BG;
    private javax.swing.JButton Jbt_abonar;
    private javax.swing.JButton Jbt_verVenta;
    private javax.swing.JLabel Jlb_buscar;
    private javax.swing.JLabel Jlb_id;
    private javax.swing.JTable Jtable_ventas;
    private javax.swing.JTextField Jtf_buscador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public void listarVenta() {
        List<Venta> listarV = vDAO.ListarVentas();
        modelo = (DefaultTableModel) Jtable_ventas.getModel();
        Object[] ob = new Object[8];
        for (int i = 0; i < listarV.size(); i++) {
            ob[0] = listarV.get(i).getId();
            ob[1] = listarV.get(i).getCliente();
            ob[2] = listarV.get(i).getVendedor();
            ob[3] = listarV.get(i).getTipo_pago();
            ob[4] = listarV.get(i).getTotal();
            ob[5] = listarV.get(i).getAbono();
            ob[6] = listarV.get(i).getSaldo();
            ob[7] = listarV.get(i).getFecha();

            modelo.addRow(ob);
        }
        Jtable_ventas.setModel(modelo);
    }

    public void BuscarVentas(String buscar) {
        LimpiarTable();
        List<Venta> listarV = vDAO.BuscarVentas(buscar);
        modelo = (DefaultTableModel) Jtable_ventas.getModel();
        Object[] ob = new Object[8];
        for (int i = 0; i < listarV.size(); i++) {
            ob[0] = listarV.get(i).getId();
            ob[1] = listarV.get(i).getCliente();
            ob[2] = listarV.get(i).getVendedor();
            ob[3] = listarV.get(i).getTipo_pago();
            ob[4] = listarV.get(i).getTotal();
            ob[5] = listarV.get(i).getAbono();
            ob[6] = listarV.get(i).getSaldo();
            ob[7] = listarV.get(i).getFecha();

            modelo.addRow(ob);
        }
        Jtable_ventas.setModel(modelo);
    }

    public void LimpiarTable() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

}
