/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import model.Movimientos;
import model.MovimientosDAO;
import model.TablaListener;
import model.Venta;
import model.VentaDAO;

/**
 *
 * @author maico
 */
public class PagarSaldo extends javax.swing.JFrame {

    Venta v = new Venta();
    VentaDAO vDao = new VentaDAO();
    Movimientos m = new Movimientos();
    MovimientosDAO mDao = new MovimientosDAO();
    private TablaListener tablaListener;

    /**
     * Creates new form CrearUsuario
     */
    public PagarSaldo() {
        initComponents();
        setIconImage(getIconImage());
        setLocationRelativeTo(null);
        Jtf_id.setVisible(false);
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Image/iconoprincipal.png"));
        return retValue;
    }

    public PagarSaldo(Venta v) {
        initComponents();
        setIconImage(getIconImage());
        setLocationRelativeTo(null);
        Jtf_id.setText(Integer.toString(v.getId()));
        Jtf_nombre.setText(v.getCliente());
        Jtf_total.setText(Double.toString(v.getTotal()));
        Jtf_saldo.setText(Double.toString(v.getSaldo()));
        Jtf_monto.setText(Double.toString(v.getAbono()));
        Jtf_id.setVisible(false);
    }

    public void setTablaListener(TablaListener listener) {
        this.tablaListener = listener;
    }

    private void limpiar() {
        Jtf_id.setText("");
        Jtf_nombre.setText("");
        Jtf_abono.setText("");
        Jtf_monto.setText("");
        Jtf_saldo.setText("");
        Jtf_total.setText("");
    }

    private void RegistrarCaja() {
        double caja = vDao.ObtenerCaja();
        caja += Double.parseDouble(Jtf_abono.getText());
        vDao.ModificarCaja(caja);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_BG = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Jlb_title = new javax.swing.JLabel();
        Jlb_nombre = new javax.swing.JLabel();
        Jtf_nombre = new javax.swing.JTextField();
        Jbn_abonar = new javax.swing.JButton();
        Jbn_atras = new javax.swing.JButton();
        Jlb_total = new javax.swing.JLabel();
        Jtf_total = new javax.swing.JTextField();
        Jtf_saldo = new javax.swing.JTextField();
        Jlb_saldo = new javax.swing.JLabel();
        Jlb_monto = new javax.swing.JLabel();
        Jtf_monto = new javax.swing.JTextField();
        Jlb_abono = new javax.swing.JLabel();
        Jtf_abono = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        Jtf_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        JP_BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Jlb_title.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        Jlb_title.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_title.setText("Abonar Saldo");

        Jlb_nombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_nombre.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_nombre.setText("Nombre:");

        Jtf_nombre.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_nombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jtf_nombre.setBorder(null);

        Jbn_abonar.setBackground(new java.awt.Color(255, 102, 0));
        Jbn_abonar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jbn_abonar.setForeground(new java.awt.Color(255, 255, 255));
        Jbn_abonar.setText("Abonar");
        Jbn_abonar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbn_abonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbn_abonarActionPerformed(evt);
            }
        });

        Jbn_atras.setBackground(new java.awt.Color(255, 102, 0));
        Jbn_atras.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Jbn_atras.setForeground(new java.awt.Color(255, 255, 255));
        Jbn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/atras.png"))); // NOI18N
        Jbn_atras.setText("Atras");
        Jbn_atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbn_atrasActionPerformed(evt);
            }
        });

        Jlb_total.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_total.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_total.setText("Total:");

        Jtf_total.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_total.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jtf_total.setBorder(null);

        Jtf_saldo.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_saldo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jtf_saldo.setBorder(null);

        Jlb_saldo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_saldo.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_saldo.setText("Saldo:");

        Jlb_monto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_monto.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_monto.setText("Monto:");

        Jtf_monto.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_monto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jtf_monto.setBorder(null);

        Jlb_abono.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_abono.setForeground(new java.awt.Color(255, 102, 0));
        Jlb_abono.setText("Abono:");

        Jtf_abono.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_abono.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jtf_abono.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(255, 102, 0));

        jSeparator2.setForeground(new java.awt.Color(255, 102, 0));

        jSeparator3.setForeground(new java.awt.Color(255, 102, 0));

        jSeparator4.setForeground(new java.awt.Color(255, 102, 0));

        jSeparator5.setForeground(new java.awt.Color(255, 102, 0));

        Jtf_id.setBackground(new java.awt.Color(255, 255, 255));
        Jtf_id.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jbn_atras))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Jbn_abonar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Jlb_nombre)
                                        .addComponent(Jlb_total)
                                        .addComponent(Jlb_saldo))
                                    .addGap(50, 50, 50)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Jlb_title)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(88, 88, 88)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jSeparator5)
                                                .addComponent(jSeparator4)
                                                .addComponent(jSeparator3)
                                                .addComponent(jSeparator2)
                                                .addComponent(Jtf_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                                .addComponent(Jtf_total, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                                .addComponent(Jtf_saldo, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                                .addComponent(Jtf_monto, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                                .addComponent(Jtf_abono, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                                .addComponent(jSeparator1)))))
                                .addComponent(Jlb_monto)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(Jlb_abono)
                                    .addGap(366, 366, 366))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jbn_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jlb_title)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_nombre)
                    .addComponent(Jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_total)
                    .addComponent(Jtf_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_saldo)
                    .addComponent(Jtf_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_monto)
                    .addComponent(Jtf_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_abono)
                    .addComponent(Jtf_abono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(Jbn_abonar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        JP_BG.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_BG, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbn_abonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbn_abonarActionPerformed
        int pregunta = JOptionPane.showConfirmDialog(null, "¿Está seguro de hacer el abono?");
        if (pregunta == 0) {
            String tipo_pago;
            double total = Double.parseDouble(Jtf_total.getText());
            double monto = Double.parseDouble(Jtf_monto.getText());
            double abono = Double.parseDouble(Jtf_abono.getText());
            double saldo = Double.parseDouble(Jtf_saldo.getText());
            int id = Integer.parseInt(Jtf_id.getText());

            if ((monto + abono) == total) {
                tipo_pago = "PAGADO";
            } else {
                tipo_pago = "CREDITO";
            }

            monto += abono;
            saldo -= abono;

            v.setTipo_pago(tipo_pago);
            v.setAbono(monto);
            v.setSaldo(saldo);
            v.setId(id);
            m.setTipo_mov("Abono");
            m.setDescripcion(" ");
            m.setMonto(abono);
            m.setId_factura(id);
            RegistrarCaja();
            mDao.RegistrarMovimiento(m);
            vDao.AbonarCredito(v);
            JOptionPane.showMessageDialog(null, "Abono realizado", "Message: Abono", JOptionPane.INFORMATION_MESSAGE);

            if (tablaListener != null) {
                tablaListener.tablaActualizada();
            }
            limpiar();
            this.dispose();
        }
    }//GEN-LAST:event_Jbn_abonarActionPerformed

    private void Jbn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbn_atrasActionPerformed
        if (tablaListener != null) {
            tablaListener.tablaActualizada();
        }
        limpiar();
        this.dispose();
    }//GEN-LAST:event_Jbn_atrasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP_BG;
    private javax.swing.JButton Jbn_abonar;
    private javax.swing.JButton Jbn_atras;
    private javax.swing.JLabel Jlb_abono;
    private javax.swing.JLabel Jlb_monto;
    private javax.swing.JLabel Jlb_nombre;
    private javax.swing.JLabel Jlb_saldo;
    private javax.swing.JLabel Jlb_title;
    private javax.swing.JLabel Jlb_total;
    private javax.swing.JTextField Jtf_abono;
    private javax.swing.JTextField Jtf_id;
    private javax.swing.JTextField Jtf_monto;
    private javax.swing.JTextField Jtf_nombre;
    private javax.swing.JTextField Jtf_saldo;
    private javax.swing.JTextField Jtf_total;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
