/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import model.NuevaVentaDAO;
import model.ProductosDAO;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
/**
 *
 * @author maico
 */
public class Principal_Usuario extends javax.swing.JFrame { 
    JP_Cliente c = new JP_Cliente();
    JP_Proveedor pro = new JP_Proveedor();
    JP_Ventas v = new JP_Ventas();
    String vendedor;
    /**
     * Creates new form Principal
     */
    public Principal_Usuario() {
        super("Bienvenido al sistema");
        setIconImage(getIconImage());
        initComponents();
        setLocationRelativeTo(null);
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Image/iconoprincipal.png"));
        return retValue;
    }
    
    public Principal_Usuario(String vendedor){
        super("Bienvenido al sistema");
        initComponents();
        setIconImage(getIconImage());
        setLocationRelativeTo(null);
        this.vendedor = vendedor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_BG = new javax.swing.JPanel();
        JP_Botones = new javax.swing.JPanel();
        Jbn_nuevaVenta = new javax.swing.JButton();
        Jbn_clientes = new javax.swing.JButton();
        Jlb_cerrarSesion1 = new javax.swing.JLabel();
        Jbn_ventas = new javax.swing.JButton();
        JP_multiPanel = new javax.swing.JPanel();
        Jlb_Bienvenida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        JP_BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JP_Botones.setBackground(new java.awt.Color(204, 204, 204));

        Jbn_nuevaVenta.setBackground(new java.awt.Color(255, 102, 0));
        Jbn_nuevaVenta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        Jbn_nuevaVenta.setForeground(new java.awt.Color(255, 255, 255));
        Jbn_nuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/N_Venta.png"))); // NOI18N
        Jbn_nuevaVenta.setText("Nueva Venta");
        Jbn_nuevaVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbn_nuevaVenta.setHideActionText(true);
        Jbn_nuevaVenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jbn_nuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbn_nuevaVentaActionPerformed(evt);
            }
        });

        Jbn_clientes.setBackground(new java.awt.Color(255, 102, 0));
        Jbn_clientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        Jbn_clientes.setForeground(new java.awt.Color(255, 255, 255));
        Jbn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Clientes.png"))); // NOI18N
        Jbn_clientes.setText("Clientes");
        Jbn_clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbn_clientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jbn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbn_clientesActionPerformed(evt);
            }
        });

        Jlb_cerrarSesion1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Jlb_cerrarSesion1.setForeground(new java.awt.Color(0, 0, 0));
        Jlb_cerrarSesion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cerrar-sesion.png"))); // NOI18N
        Jlb_cerrarSesion1.setText("Cerrar Sesión");
        Jlb_cerrarSesion1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jlb_cerrarSesion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jlb_cerrarSesion1MouseClicked(evt);
            }
        });

        Jbn_ventas.setBackground(new java.awt.Color(255, 102, 0));
        Jbn_ventas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        Jbn_ventas.setForeground(new java.awt.Color(255, 255, 255));
        Jbn_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Ventas.png"))); // NOI18N
        Jbn_ventas.setText("Ventas");
        Jbn_ventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbn_ventas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jbn_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbn_ventasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_BotonesLayout = new javax.swing.GroupLayout(JP_Botones);
        JP_Botones.setLayout(JP_BotonesLayout);
        JP_BotonesLayout.setHorizontalGroup(
            JP_BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_BotonesLayout.createSequentialGroup()
                .addGroup(JP_BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_BotonesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(JP_BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jbn_nuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jbn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jbn_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JP_BotonesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jlb_cerrarSesion1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        JP_BotonesLayout.setVerticalGroup(
            JP_BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_BotonesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Jbn_nuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Jbn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Jbn_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 400, Short.MAX_VALUE)
                .addComponent(Jlb_cerrarSesion1)
                .addContainerGap())
        );

        JP_BG.add(JP_Botones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 660));

        JP_multiPanel.setBackground(new java.awt.Color(255, 255, 255));

        Jlb_Bienvenida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Image_bienvenida.png"))); // NOI18N

        jLabel1.setText("By: Michael Coral");

        javax.swing.GroupLayout JP_multiPanelLayout = new javax.swing.GroupLayout(JP_multiPanel);
        JP_multiPanel.setLayout(JP_multiPanelLayout);
        JP_multiPanelLayout.setHorizontalGroup(
            JP_multiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_multiPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Jlb_Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_multiPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        JP_multiPanelLayout.setVerticalGroup(
            JP_multiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_multiPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Jlb_Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        JP_BG.add(JP_multiPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1050, 660));

        jPanel1.setBackground(new java.awt.Color(72, 92, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        JP_BG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1350, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JP_BG, javax.swing.GroupLayout.PREFERRED_SIZE, 1350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbn_nuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbn_nuevaVentaActionPerformed
        Jbn_nuevaVenta.setBackground(Color.GRAY);
        Jbn_clientes.setBackground(new Color(255,102,0)); 
        Jbn_ventas.setBackground(new Color(255,102,0));
        JP_NuevaVenta nv = new JP_NuevaVenta(vendedor);
        AutoCompleteDecorator.decorate(nv.Jtf_producto, new NuevaVentaDAO().productos_Autocom(), true);
        AutoCompleteDecorator.decorate(nv.Jtf_codigo, new NuevaVentaDAO().codigos_Autocom(), true);
        
        nv.setSize(1050,660);
        
        JP_multiPanel.removeAll();
        JP_multiPanel.add(nv);
        JP_multiPanel.revalidate();
        JP_multiPanel.repaint();
    }//GEN-LAST:event_Jbn_nuevaVentaActionPerformed

    private void Jbn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbn_clientesActionPerformed
        Jbn_nuevaVenta.setBackground(new Color(255,102,0));
        Jbn_ventas.setBackground(new Color(255,102,0));
        Jbn_clientes.setBackground(Color.GRAY);
        
        c.LimpiarTable();
        c.ListarCliente();
        c.setSize(1050,660);
        
        JP_multiPanel.removeAll();
        JP_multiPanel.add(c);
        JP_multiPanel.revalidate();
        JP_multiPanel.repaint();
    }//GEN-LAST:event_Jbn_clientesActionPerformed

    private void Jlb_cerrarSesion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlb_cerrarSesion1MouseClicked
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jlb_cerrarSesion1MouseClicked

    private void Jbn_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbn_ventasActionPerformed
        Jbn_nuevaVenta.setBackground(new Color(255,102,0));
        Jbn_clientes.setBackground(new Color(255,102,0));
        Jbn_ventas.setBackground(Color.GRAY);
        
        v.LimpiarTable();
        v.listarVenta();
        v.setSize(1050,660);
        
        JP_multiPanel.removeAll();
        JP_multiPanel.add(v);
        JP_multiPanel.revalidate();
        JP_multiPanel.repaint();
    }//GEN-LAST:event_Jbn_ventasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP_BG;
    private javax.swing.JPanel JP_Botones;
    private javax.swing.JPanel JP_multiPanel;
    private javax.swing.JButton Jbn_clientes;
    private javax.swing.JButton Jbn_nuevaVenta;
    private javax.swing.JButton Jbn_ventas;
    private javax.swing.JLabel Jlb_Bienvenida;
    private javax.swing.JLabel Jlb_cerrarSesion1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
